# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c23fb57d5734f0bed95ad280c7a89a8e9dc223ac51379e6ab1028b48a33e5619222b4fce9ee55b4a96cd5972d28d9b106bc937925474ee265535fb845ed885c

test:
  secret_key_base: fd12478bdfdaad6f3e06589530a2b54c616e78d2f40b3e5f36848885dbc2e3b7bb6cefb83f15705e54a1dce8fbc26e8692ab5e3dae27a8ca1707c68a9ad3872b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
